### PR TITLE
Add a basic memory protection scheme

### PR DESCRIPTION
**Pull request by antoinealb**
I tested the code at work, but I don't have access to a real board for testing it.

Can somebody make it run on real hardware ? @Stapelzeiger @nuft @froj ?

Original idea (a long time ago) by @31415us

### CODE REVIEW

**Comment by SyrianSpock** [comment]
We need to test this and merge ASAP @antoinealb @Stapelzeiger @nuft

**Comment by nuft** [comment]
This probably should be replaced by [cvra/arm-cortex-tools](https://github.com/cvra/arm-cortex-tools)

**Comment by nuft** [comment]
I can take care of that.

**Comment by SyrianSpock** [comment]
Thanks

**Pull request closed without merging**
