### PR TITLE
Improve boot time

### PR DESCRIPTION
**Pull request by nuft**

### CODE REVIEW

**Comment by Stapelzeiger** [comment]
tested?

**Comment by nuft** [comment]
If the SerialUSB driver isn't used from the threads started before the driver, there won't be an issue.
Yes, I tested it. Things still work and the delay after reset feels shorter.

**Comment by SyrianSpock** [comment]
Is this still relevant ? @nuft @Stapelzeiger

**Comment by nuft** [comment]
In the end USB probably won't be used for deployment.

**Pull request closed without merging**
