### PR TITLE
New code organization

### PR DESCRIPTION
**Pull request by nuft**
This PR is to start the discussion on how to organise the codebase.

### CODE REVIEW

**Comment by nuft** [comment]
some major points:
* one main repository for the two robots (one checkout that defines all the code that is run for a match)
* minimal number of submodules (avoid nested submodules)
* build for multiple firmwares -> one common version of code & datatypes (UAVCAN, msgbus, ...)
* avoid code duplication

for the moment this completely breaks the build and CI. I'll fix this later.

**Comment by antoinealb** [comment]
Agree with those changes. Also it should be easy (`make` from root of the project) to build the firmware used for the two robots.

**Comment by SyrianSpock** [comment]
Agree with all of the above.

**Comment by nuft** [comment]
I fixed the CI builds. Can we merge?

**Comment by nuft** [comment]
Migrated to [cvra/robot-software](https://github.com/cvra/robot-software)

**Comment by nuft** [comment]
Migrated to [cvra/robot-software](https://github.com/cvra/robot-software)

**Pull request closed without merging**
