### PR TITLE
Rewrite port layer + update lwIP

### PR DESCRIPTION
**Pull request by antoinealb**
I am currently chasing the bugs we had with the master firmware, and to do this I rewrote the port layer and updated lwip to their current master. It seems to greatly improve the stability of the system, although I am not sure if the old version or ChibiOS' integration is to blame here.

I still had one hardfault when testing after about 20 minutes of streaming pretty heavy traffic (about 3MB/s I think), I am trying to reproduce it.

### CODE REVIEW

**Comment by antoinealb** [comment]
So I was able to run a 6h test, in which I exchanged 1M UDP packets (about 30GB) without any problems. There was also some minor ICMP traffic. I would say it is pretty stable now. Too bad I only found this after the  contest :angry:

**Comment by antoinealb** [comment]
Bump, anybody interested in working on this ?

**Comment by antoinealb** [comment]
So apparently it increased ip + uavcan reliability but broke CAN bridge. Working on debugging it.

**Comment by Stapelzeiger** [comment]
The can bridge is broken because of a failed allocation (that wasn't checked!) which then triggered a NULL argument assert. The failing allocation is at ```can_bridge.c:107```.

**Comment by Stapelzeiger** [comment]
I can confirm that the can bridge now works again. I had to free up some RAM space. I removed the ChibiOS test suite from our build which frees about 25k of flash and 3k RAM.

**Comment by antoinealb** [comment]
Updated pull request with your changes.

**Pull request merged**
